export const TodosActionTypes = {
  CREATE_TODO_STARTED: "[TODO] CREATE_TODO_STARTED",
  CREATE_TODO_SUCCESS: "[TODO] CREATE_TODO_SUCCESS",
  CREATE_TODO_ERROR: "[TODO] CREATE_TODO_ERROR",
  CREATE_TODO_OFFLINE: "[TODO] CREATE_TODO_OFFLINE",
};
